### ISSUE TITLE
Insecure platform warning

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/newsreader-api#12]
I get this message when running locally:

"""
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): knowledgestore2.fbk.eu
/home/ian/.virtualenvs/newsreader-new-api/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
"""

**Comment by pwaller** [comment]
That's because your version of Ubuntu has an old version of Python installed, and not a problem with newsreader, sadly :(

http://stackoverflow.com/questions/29572161/how-to-securely-use-pip-with-ssl-on-ubuntu-trusty/30651388#comment49435705_30651388

The pip developers *could not make pip secure* with that version of python. It seems not something that Ubuntu is likely to fix in LTS any time quickly, as far as I have been able to tell.

**Comment by StevenMaude** [comment]
@IanHopkinson A workaround is to do `pip install requests[security]` — you'll still get the warning for that installation, but subsequent ones won't complain. You may need to do [`apt-get install libffi-dev libssl-dev`](https://stackoverflow.com/a/29202163) first.

**Comment by pwaller** [comment]
:+1: you could post that on the SO post, @StevenMaude. It still leaves one open to attack during the first run, but that's better than being permanently open :)

**Comment by StevenMaude** [comment]
@pwaller: Will do; from the PyPI dev post in the one you linked, it sounds like they've handled the issues server-side, so the warning's not as bad as it seems (though it's still not ideal, and I'm inclined to copy you regarding LTS, and switch away from it when I next install a new OS).
