### ISSUE TITLE
Mechanism for storing credentials fails for multiple endpoints

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/newsreader-api#9]
Currently the NEWSREADER_USERNAME and NEWSREADER_PASSWORD are stored in environment variables, but there is only one such pair therefore we can't address multiple SPARQL endpoints with different credentials.

**Comment by StevenMaude** [comment]
One option is to have separate variables for each endpoint which seems a bit too specific.

The better way is maybe make those environment variables store stringified JSON:

```
{"public_endpoint": "public_username", "private_endpoint": "private_username"}
```

and then specify the endpoint depending on which data set we're looking at somewhere.

(This will take me a bit longer to figure out where; haven't looked at the main Newsreader code since start of the year!)

**Comment by IanHopkinson** [comment]
For some reason storing stringified JSON in an environment variable just seems wrong to me!

**Comment by StevenMaude** [comment]
Temporary fix if it's urgent for the Newsreader meeting is just switch to the House of Representatives endpoint credentials, provided they don't need the cars data to be available simultaneously. All this involves is a `./cfn.sh update <current newsreader stack name>` running with the appropriate environment variables set.

**Comment by StevenMaude** [comment]
Rather than sticking all the info into one environment variable, we could have NEWSREADER_PRIVATE_USERNAME, NEWSREADER_PUBLIC_USERNAME and a PASSWORD for both.

**Comment by StevenMaude** [comment]
We also should have separate public and private API keys.

**Comment by StevenMaude** [comment]
In principle, JSON in environment variable would be OK.

But, as mentioned by @pwaller:

* JSON as env variable for deployment would be fun since commas aren't allowed by CloudFormation.
* Using s3 to store credentials was also suggested; advantages: no need for credentials to deploy, no chance for someone to deploy with wrong credentials.

**Comment by StevenMaude** [comment]
For now, the two endpoint handling is fine. If running end-to-end, we may need to support multiple endpoints more flexibly.

**Comment by StevenMaude** [comment]
Fixed for now in https://github.com/scraperwiki/newsreader-api/pull/23.
